#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar  9 17:15:23 2023

@author: nikhilsama
"""

TODO 

1) Check graph of PE/CE/Price to see if it moves minute by minute w bol bands
-- Also check minute volume candles for PE/CE to ensure these is enough volume .. at least 30 lacs on a minute candle (so we can take 30%)
2) Add in logic for long and short via PE/CE in performance



CHECK 
Why didint we exit bajaj fin at 10:13, good we didnnt, but why ? 
fast ma was belwo and it wasnt trending
Bad -- Exited bajaj fin at 10:29 when it hit uppper bb.  Dont look at BB for trending stocks -- change to be made
